### ISSUE TITLE
FORGE server error

### ISSUE THREAD

**Issue by Ramnck** [heyValdemar/minecraft-server-docker-compose#2]
Hello. An error occurring while initializing server type of FORGE. used image:itzg/minecraft-server:java17-openj9
Error itself:
```bash
minecraft-server         | Exception in thread "main" java.lang.IllegalStateException: Open J9 is not supported
minecraft-server         |      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
minecraft-server         |      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
minecraft-server         |      at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
minecraft-server         |      at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
minecraft-server         | 2022-12-01T16:08:18.552Z     WARN    mc-server-runner        Minecraft server process failed {"exitCode": 1}
```

**Comment by heyvaldemar** [comment]
I would recommend you to use `itzg/minecraft-server:latest`.
